server:
  port: 8401
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 30000 #服务请求连接超时时间（毫秒） 30s
  ReadTimeout: 3600000 #服务请求处理超时时间（毫秒） 30min
